version: '3'

services:
  
  app:
    build: ./WebApp
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - keys:/etc/keys

  postgres:
    env_file: .env
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  redis:
    image: redis:3.2

volumes:
  db-data:
  keys:
